# This needs to be an OAuth 2.0 ID: https://console.developers.google.com/apis/credentials
oauth:
  credentials_path: credentials/oauth-credentials.json
  token_path: credentials/token.json
  scopes:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/documents
    - https://www.googleapis.com/auth/spreadsheets
    - https://www.googleapis.com/auth/gmail.send

invoice:
  # Leave empty to get year from system time
  year:
  # Leave empty to get month from system time
  month:
  template_doc_id: 1DTDvMk7g-bS_LM0tEijcijxUee6SIN1esTywyeW__hs
  # Set target_folder to empty to automatically use a folder by year
  target_folder: # 1JgtKVhl7LLll1und9xDjxWunXRQGp__b
  invoice_log:
    sheet_id: 1lCme-GkRjgsAWzYfvOx3yEN-W8JzrYnxfcPMk2q4sYw
    tab: Facturen

recipients:
  sheet_id: 1lCme-GkRjgsAWzYfvOx3yEN-W8JzrYnxfcPMk2q4sYw
  tab: Factuurgegevens
  range: "A:J"
  is_active:
    column: Actief (vink deze optie aan alsjeblieft)
    true_value: [Ja, ja, Actief lid]

  # Templated value lookups: the values below are column headers in the spreadsheet.
  # The 'email' value is to be looked up in the column "Email"
  name: Naam
  email: E-mailadres
  address: Adres
  postcode: Postcode
  city: Woonplaats
