# This needs to be an OAuth 2.0 ID: https://console.developers.google.com/apis/credentials
oauth:
  credentials_path: credentials/oauth-credentials.json
  token_path: credentials/token.json
  scopes:
    - https://www.googleapis.com/auth/documents
    - https://www.googleapis.com/auth/spreadsheets

invoice:
  template_doc_id: 1DTDvMk7g-bS_LM0tEijcijxUee6SIN1esTywyeW__hs
  invoice_log:
    sheet_id: 1lCme-GkRjgsAWzYfvOx3yEN-W8JzrYnxfcPMk2q4sYw
    tab: "Facturen"

recipients:
  sheet_id: 1lCme-GkRjgsAWzYfvOx3yEN-W8JzrYnxfcPMk2q4sYw
  tab: Ledenlijst
  range: "A:F"
  is_active:
    column: Actief
    true_value: [Ja, ja]

  # Templated value lookups: the values below are column headers in the spreadsheet.
  # The 'email' value is to be looked up in the column "Email"
  email: Email
  address: Adres
  postcode: Postcode
  city: Plaats
